# примеры API-запросов

@baseUrl = http://localhost:8000/api

# Создания и регистрация пользователя 
POST  {{baseUrl}}/users
Content-Type: application/json

{
    "user": {
        "username": "Pavel222",
        "email": "pavel222@mail.ru",
        "password": "222222888"
    }
}

###
# авторизация пользователя 
POST {{baseUrl}}/users/login/
Content-Type: application/json


{
    "user": {
        "email": "pavel222@mail.ru",
        "password": "222222888"
    }
}

###
# получение пользователя
GET {{baseUrl}}/users/
Content-Type: application/json
Authorization:Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzUyNjc5Mzc3fQ.1NNW2-1hludPmHDOJmc8I020tQ69Pj_gQ9oVKKV_EqA

###
# попытка поменять пользователя
PATCH {{baseUrl}}/users/
Content-Type: application/json
Authorization:Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZXhwIjoxNzU1MjQ3MTI2fQ.6YfauPdoRLeiat1P9BuK5d4k6fPfRpFug4pEJqxNxTE


{
    "user": {
        "email": "Pavel0003@mail.ru",
        "password": "00000000"
    }
}

###

# получение списка магазинов 
GET  {{baseUrl}}/shops/
Content-Type: application/json

###

# получение списка категорий
GET  {{baseUrl}}/categories/
Content-Type: application/json


###
# получения продуктов
GET  {{baseUrl}}/product/?shop=3&сategory=1
Content-Type: application/json

###
# получения корзины 
GET  {{baseUrl}}/cart/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzUyNjg2NDIyfQ.j9pE5LXcH4Kb7aWF5mTDMnzIq8zrYbjjZyJ8fnCS09M

###
# добавление товара в корзину 
POST   {{baseUrl}}/cart/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzUyNjg2NDIyfQ.j9pE5LXcH4Kb7aWF5mTDMnzIq8zrYbjjZyJ8fnCS09M

{
    "product": 1,
    "quantity": 400
}

###
# изменения товара в корзину 
PUT    {{baseUrl}}/cart/47/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzUyNjg2NDIyfQ.j9pE5LXcH4Kb7aWF5mTDMnzIq8zrYbjjZyJ8fnCS09M

{
    "product": 1,
    "quantity": 100
}

###
# удаление товара из корзины 
DELETE   {{baseUrl}}/cart/47/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZXhwIjoxNzUyNjg4ODY3fQ.5CTiuJ8WZKKVBUuwqT-h3_nj7nlcPAP2HARMhHgd528

###

# Оформление заказа товара в корзине
POST  {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZXhwIjoxNzUyNjg4ODY3fQ.5CTiuJ8WZKKVBUuwqT-h3_nj7nlcPAP2HARMhHgd528

###
# Получение моих заказов
GET   {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNzUyNjg2NDIyfQ.j9pE5LXcH4Kb7aWF5mTDMnzIq8zrYbjjZyJ8fnCS09M

###
# обновления прайс листа
POST    {{baseUrl}}/update/
Content-Type: application/json


