# примеры API-запросов
# в поле Authorization подставить JWT токен полученый при регистрации

@baseUrl = http://localhost:8000/api

# Создания и регистрация пользователя 
POST  {{baseUrl}}/users
Content-Type: application/json

{
    "user": {
        "username": "Pavel222",
        "email": "pavel222@mail.ru",
        "password": "222222888"
    }
}

###
# авторизация пользователя 
POST {{baseUrl}}/users/login/
Content-Type: application/json


{
    "user": {
        "email": "pavel222@mail.ru",
        "password": "222222888"
    }
}

###
# получение пользователя
GET {{baseUrl}}/users/
Content-Type: application/json
Authorization:Token 

###
# попытка поменять пользователя
PATCH {{baseUrl}}/users/
Content-Type: application/json
Authorization:Token 


{
    "user": {
        "email": "Pavel0003@mail.ru",
        "password": "00000000"
    }
}

###

# получение списка магазинов 
GET  {{baseUrl}}/shops/
Content-Type: application/json

###

# получение списка категорий
GET  {{baseUrl}}/categories/
Content-Type: application/json


###
# получения продуктов
GET  {{baseUrl}}/product/?shop=3&сategory=1
Content-Type: application/json

###
# получения корзины 
GET  {{baseUrl}}/cart/
Content-Type: application/json
Authorization: Token 

###
# добавление товара в корзину 
POST   {{baseUrl}}/cart/
Content-Type: application/json
Authorization: Token 

{
    "product": 1,
    "quantity": 400
}

###
# изменения товара в корзину 
PUT    {{baseUrl}}/cart/47/
Content-Type: application/json
Authorization: Token 

{
    "product": 1,
    "quantity": 100
}

###
# удаление товара из корзины 
DELETE   {{baseUrl}}/cart/47/
Content-Type: application/json
Authorization: Token 

###

# Оформление заказа товара в корзине
POST  {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 

###
# Получение моих заказов
GET   {{baseUrl}}/order/
Content-Type: application/json
Authorization: Token 

###
# обновления прайс листа
POST    {{baseUrl}}/update/
Content-Type: application/json


